### PR TITLE
Remove the warning 'rvm_chef_user_environment.rb:49: warning: class variable access from toplevel'

### PR DESCRIPTION
**Pull request by alexfalkowski**
....

### CODE REVIEW

**Comment by digitalecho** [comment]
Any movement on this? I'd love to see it merged in. Logs are a bit deceiving being polluted by this error.

**Comment by alexfalkowski** [comment]
They have a lot of pull requests. I have no idea where this is at.

**Comment by alexandre-zia-movile** [comment]
I've applied this patch and it didn't work, it broke chef-run with:
```(rvm::system line 39) had an error: NameError: uninitialized class variable @@root_rvm_path in Object```

**Comment by alexfalkowski** [comment]
I'm happy for some one to try to help diagnose this, unfortunately I don't use chef anymore.

**Pull request closed without merging**
